apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
      - name: logoutput
        image: k3s-default-registry:5000/log-output:latest
        resources:
          limits:
            cpu: 50m
            memory: 64M
      
