apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: logoutput
          image: k3s-default-registry:5000/ping-pong:v0.1
          resources:
            limits:
              cpu: 50m
              memory: 64M
