apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: mypvc
      containers:
        - name: project
          image: k3s-default-registry:5000/project:v0.7
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - name: shared-image
              mountPath: /usr/src/app/files
